### ISSUE TITLE
郭丽的github帐号

### ISSUE THREAD

**Issue by lilyjy007** [Lihuanghe/CMCCTraineeProject#3]
lilyjy007
2232701617@qq.com
https://github.com/lilyjy007/testgit

**Comment by Lihuanghe** [comment]
怎么把整个maven的可执行包都传上去了。只传代码就行。

**Comment by lilyjy007** [comment]
那个是我试验用的，不是我的代码，我等会把没用的都删了。

**Comment by lilyjy007** [comment]
那个是我试验用的，不是我的代码，我等会把没用的都删了。

**Comment by Lihuanghe** [comment]
https://github.com/lilyjy007
